theme: jekyll-theme-minimal

title: Andrea Giusto

description: PhD student at DIBRIS department of University of Genoa, Italy, supervised by Francesco Dagnino.<br><br>Email address: <em>andrea.giusto@edu.unige.it
